### DISCUSSION TITLE
Is it possible to add more attributes to a node?

### DISCUSSION THREAD

**Discussion by schultzp2020** [markdoc/markdoc#146] [Q&A] [answered]
Is it possible to add more attributes to a node?

For example, I want to have an option to add a title and a filename for a fence like this. 
```
\```yaml title="Adding an `openshift` component using the `uri` property" filename="devfile.yaml"
components:
  - name: mysql
    openshift:
      uri: petclinic.yaml
\```
```

I could probably get around this by using a custom tag around the fence; however, for simplicity purposes, I was wonder if the example above was possible.

**Comment by mfix-stripe** [comment, marked as answer]
@schultzp2020 you can do:

\```yaml {% title="Adding an `openshift` component using the `uri` property" filename="devfile.yaml" %}
components:
  - name: mysql
    openshift:
      uri: petclinic.yaml
\```

You will just need to configure the `fence` node to allow `title` and `filename` as valid attributes.

**Reply by schultzp2020** [reply]
@mfix-stripe That did not work as expected.

![image](https://user-images.githubusercontent.com/52387464/180859615-1b12b0a0-5828-4346-bbdf-97271084a2b7.png)

```md
## Procedure

1. Define a component using the `kubernetes` or `openshift` property.

2. Provide the content through the `uri` or `inlined` property.

    **Adding an `openshift` component using the `uri` property**

    ```yaml {% title="Adding an openshift component using the `uri` property" filename="devfile.yaml" %}
    components:
      - name: mysql
        openshift:
          uri: petclinic.yaml
    ```

    **Adding a `kubernetes` component using the `inlined` property**

    ```yaml
    components:
    - name: myk8deploy
      kubernetes:
        inlined:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: pi
          spec:
            template:
              spec:
                containers:
                - name: job
                  image: myimage
                  command: ["some",  "command"]
                restartPolicy: Never
    ```
```

```tsx
import { Fence } from '@devfile-web/core';

const nodes = {
  fence: {
    render: Fence,
    attributes: {
      language: {
        type: String,
      },
      title: {
        type: String || undefined,
      },
      filename: {
        type: String || undefined,
      },
    },
  },
};

export default nodes;
```

Then I tried to console log the prop in `<Fence>` but it was an empty object.
