### DISCUSSION TITLE
Markdoc language server not adding executable to path

### DISCUSSION THREAD

**Discussion by Sporiff** [markdoc/markdoc#525] [Bug report]
I'm trying to configure Markdoc to work with the [Helix editor](https://helix-editor.com) using the Markdoc LSP. I'm installing the LSP using `npm i -g @markdoc/language-server` per [Helix's instructions](https://github.com/helix-editor/helix/wiki/Language-Server-Configurations#markdoc). However, it seems like installing the LSP like this doesn't add anything to my PATH. I would expect to see `markdoc-ls` in my PATH somewhere as I do with e.g. `@mdx-js/language-server`.

**Comment by mulan-stripe** [comment]
Interesting, is the output of `npm root -g` the same as your PATH ?

**Reply by Sporiff** [reply]
@mulan-stripe The output of `npm root -g` is `/opt/homebrew/lib/node_modules`. I'm running macOS Sequoia on an M-Series MacBook for context.

In other cases, such as `@mdx-js/language-server`, installing with `npm i -g @mdx-js/language-server` installs the package to `/opt/homebrew/lib/node_modules` and symlinks the executable to `/opt/homebrew/bin/mdx-language-server`. This isn't the case for `markdoc-ls`. Even if I add `/opt/homebrew/lib/node_modules` to my path the executable isn't available.

**Reply by Sporiff** [reply]
Just an update to this: I also tried installing the LSP on my Pop_OS! machine and the same issue occurs. There is no exported binary for me to hook into with my editor.

**Comment by Sporiff** [comment]
Another update to this. I have the LSP partially working in Helix by symlinking the `wrapper.js` to `.local/bin/markdoc-ls` with the following configuration:

```toml
[language-server.markdoc-ls]
command = "markdoc-ls"
args = ["--stdio"]

[language-server.markdoc-ls.config]
root = "/home/sporiff/git/dev-docs"
path = "src/content/docs"

[language-server.markdoc-ls.config.config]
root= "/home/sporiff/git/dev-docs"
path = "src/content/docs"

[[language]]
name = "markdoc"
scope = "source.markdoc"
injection-regex = "markdoc"
file-types = ["mdoc"]
language-servers = ["markdoc-ls"]
roots = ["package.json", "markdoc.config.mjs", "markdoc.config.json"]
```

However, just like in VS Code it's not actually doing what I expect (e.g. highlighting incorrect attributes). In my Helix logs, I keep seeing this message appear when I open a .mdoc file.

```
helix_term::application [WARN] Ignoring a client/registerCapability request because dynamic capability registration is not enabled. Please report this upstream to the
       │ language server
```
